//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renewal.Application.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Renewal.Application.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found Financial detail.
        /// </summary>
        internal static string Financial_Not_Found {
            get {
                return ResourceManager.GetString("Financial_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Financial detail successfully.
        /// </summary>
        internal static string Financial_Successfully {
            get {
                return ResourceManager.GetString("Financial_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update bank account processing data unsuccessful.
        /// </summary>
        internal static string ProcessingData_Update_Bank_Account_Error {
            get {
                return ResourceManager.GetString("ProcessingData_Update_Bank_Account_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update bank account processing data successfully.
        /// </summary>
        internal static string ProcessingData_Update_Bank_Account_Success {
            get {
                return ResourceManager.GetString("ProcessingData_Update_Bank_Account_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update payment method processing data unsuccessful.
        /// </summary>
        internal static string ProcessingData_Update_Payment_Method_Error {
            get {
                return ResourceManager.GetString("ProcessingData_Update_Payment_Method_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update payment method processing data successfully.
        /// </summary>
        internal static string ProcessingData_Update_Payment_Method_Success {
            get {
                return ResourceManager.GetString("ProcessingData_Update_Payment_Method_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update transaction processing data unsuccessful.
        /// </summary>
        internal static string ProcessingData_Update_Status_Error {
            get {
                return ResourceManager.GetString("ProcessingData_Update_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status processing data successful.
        /// </summary>
        internal static string ProcessingData_Update_Status_Success {
            get {
                return ResourceManager.GetString("ProcessingData_Update_Status_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update transaction processing data successfully.
        /// </summary>
        internal static string ProcessingData_Update_Transaction_Error {
            get {
                return ResourceManager.GetString("ProcessingData_Update_Transaction_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update transaction processing data successfully.
        /// </summary>
        internal static string ProcessingData_Update_Transaction_Success {
            get {
                return ResourceManager.GetString("ProcessingData_Update_Transaction_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify payment infor unsuccessful.
        /// </summary>
        internal static string ProcessingData_Verify_Payment_Infor_Error {
            get {
                return ResourceManager.GetString("ProcessingData_Verify_Payment_Infor_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify payment infor successfully.
        /// </summary>
        internal static string ProcessingData_Verify_Payment_Infor_Success {
            get {
                return ResourceManager.GetString("ProcessingData_Verify_Payment_Infor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, those details don&apos;t match our records. Please enter the policyholder&apos;s details as they appear on the renewal invitation.
        /// </summary>
        internal static string Verification_BirthDate_Invalid {
            get {
                return ResourceManager.GetString("Verification_BirthDate_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, those details don&apos;t match our records. Please enter the policyholder&apos;s details as they appear on the renewal invitation.
        /// </summary>
        internal static string Verification_FirstName_Invalid {
            get {
                return ResourceManager.GetString("Verification_FirstName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, those details don&apos;t match our records. Please enter the policyholder&apos;s details as they appear on the renewal invitation.
        /// </summary>
        internal static string Verification_Reference_Number_Invalid {
            get {
                return ResourceManager.GetString("Verification_Reference_Number_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get verification questions successfully.
        /// </summary>
        internal static string Verification_Successfully {
            get {
                return ResourceManager.GetString("Verification_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, those details don&apos;t match our records. Please enter the policyholder&apos;s details as they appear on the renewal invitation.
        /// </summary>
        internal static string Verification_Surname_Invalid {
            get {
                return ResourceManager.GetString("Verification_Surname_Invalid", resourceCulture);
            }
        }
    }
}
